name = "hci-v3"
compatibility_date = "2024-02-15"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
output_dir = ".next"

[site]
bucket = ".next"

[env.production]
name = "hci-v3-production"

[env.preview]
name = "hci-v3-preview" 